name: 'auto-git-repo-commiter'
author: 'Thamognya Kodi'
description: 'Action for auto-commiting.'
branding:
  icon: 'git-commit'
  color: 'red'
inputs:
  source-repo:
    description: 'SSH URL of the source repo.'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-repo }}
